<a href="https://colab.research.google.com/github/hadilbelhadjhassin/gomycode/blob/main/Let's_test_your_Python_skills_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#question 1
for i in range(2000,3201,1):
  if (i%7==0 and i%5!=0):
    print(i , end=', ')

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199, 

In [18]:
#question 2
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
n=int(input("Input a number to compute the factiorial : "))
print(factorial(n))

Input a number to compute the factiorial : 4
24


In [15]:
#question3
n=int(input("enter the length of dictionnary"))
d={}

for i in range (1,n+1):
  d[i]=i*i
print(d)



enter the length of dictionnary5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [17]:
#question4
def remove_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
print(remove_char('kitten', 0))
print(remove_char('kitten', 3))
print(remove_char('kitten', 5))


itten
kiten
kitte


In [16]:
#question5
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())


Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [24]:
#question6
import numpy as np
  
  
array1 = np.array([0, 1, 2])
array2 = np.array([2, 1, 0])
  
# Original array1
print(array1)
  
# Original array2
print(array2)
  
# Covariance matrix
print("\nCovariance matrix of the said arrays:\n",
      np.cov(array1, array2))


[0 1 2]
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [27]:
#question7
import math
C=50
H=30
x = [int(x) for x in input("Enter three value: ").split(",")]
 
x1=[]
for i in range (len(x)):
   Q = math.sqrt((2 * C * x[i])/H)
   x1.append(round(Q))
print(*x1, sep=",")

Enter three value: 100,150,180
18,22,24
