<a href="https://colab.research.google.com/github/hadilbelhadjhassin/gomycode/blob/main/Let's_build_create_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#question 1
import numpy as np
a=np.array([(2, 2, 3), (4, 5,6)])
print(a)
print(a.tolist())


[[2 2 3]
 [4 5 6]]
[[2, 2, 3], [4, 5, 6]]


In [ ]:
#question 2
#method 1
a = np.array([(1, 2,5), (3, 4,8), (5,6,10)])
b=0
for i in range(len(a)):
  b+=a[i,i]
print(b)

15


In [ ]:
#question 2
#method 2
c=np.trace(a)
print(c)

15


In [ ]:

#question 3
import numpy as np

a = np.array([(1, 2,5), (3, 4,8), (5,6,10)])
g=int(input())
b=a[a>g]
for i in b:
  print(i , end =' ')
print("higher than ",g) 





5
8 6 10 higher than  5


In [ ]:
#question 4

m = np.arange(6).reshape(2,3)
n=  np.arange(0,12,2).reshape(2,3)
print(m)
print(n)
C=m+n
print(C)

[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  3  6]
 [ 9 12 15]]


In [ ]:
#question 5
a = np.array([(1, 2,5), (3, 4,8), (5,6,10)])
Y = a - a.mean(axis=1, keepdims=True)
print(Y)

[[-1.66666667 -0.66666667  2.33333333]
 [-2.         -1.          3.        ]
 [-2.         -1.          3.        ]]
